/**
 * Bridal dress catalogue — Pronovias, Maggie Sottero, Richard Designs
 *
 * To use real dress photos:
 *   1. Host the dress PNG (transparent background) on your server, e.g. /assets/dresses/elvira.png
 *   2. Set imageUrl to that path on the relevant entry below
 *   3. The app will use the real image instead of the SVG silhouette
 */

const DRESSES = [

    /* ── PRONOVIAS ──────────────────────────────────────────────── */
    {
        id: 'p-elvira',
        name: 'Elvira',
        designer: 'pronovias',
        designerLabel: 'Pronovias',
        style: 'mermaid',
        color: '#f5efe8',
        description: 'Chantilly lace mermaid with statement cathedral train',
        imageUrl: null,
    },
    {
        id: 'p-blair',
        name: 'Blair',
        designer: 'pronovias',
        designerLabel: 'Pronovias',
        style: 'aline',
        color: '#fff9f3',
        description: 'Deep V A-line with illusion lace sleeves',
        imageUrl: null,
    },
    {
        id: 'p-asel',
        name: 'Asel',
        designer: 'pronovias',
        designerLabel: 'Pronovias',
        style: 'ballgown',
        color: '#fffcf7',
        description: 'Princess ballgown with 3D floral embroidery',
        imageUrl: null,
    },
    {
        id: 'p-babi',
        name: 'Babi',
        designer: 'pronovias',
        designerLabel: 'Pronovias',
        style: 'sheath',
        color: '#f0ebe2',
        description: 'Sleek sheath gown with mikado overlay',
        imageUrl: null,
    },
    {
        id: 'p-dorin',
        name: 'Dorin',
        designer: 'pronovias',
        designerLabel: 'Pronovias',
        style: 'aline',
        color: '#faf5ee',
        description: 'Romantic A-line with guipure lace bodice',
        imageUrl: null,
    },
    {
        id: 'p-tamy',
        name: 'Tamy',
        designer: 'pronovias',
        designerLabel: 'Pronovias',
        style: 'mermaid',
        color: '#f7f2ec',
        description: 'Modern mermaid with off-shoulder neckline',
        imageUrl: null,
    },

    /* ── MAGGIE SOTTERO ─────────────────────────────────────────── */
    {
        id: 'm-rebecca',
        name: 'Rebecca',
        designer: 'maggie-sottero',
        designerLabel: 'Maggie Sottero',
        style: 'ballgown',
        color: '#fff9f9',
        description: 'Classic ballgown with sweetheart neckline',
        imageUrl: null,
    },
    {
        id: 'm-antonia',
        name: 'Antonia',
        designer: 'maggie-sottero',
        designerLabel: 'Maggie Sottero',
        style: 'mermaid',
        color: '#f5f0ef',
        description: 'Fitted lace mermaid with sweep train',
        imageUrl: null,
    },
    {
        id: 'm-priya',
        name: 'Priya',
        designer: 'maggie-sottero',
        designerLabel: 'Maggie Sottero',
        style: 'aline',
        color: '#fffbf0',
        description: 'Boho A-line with floral lace and open back',
        imageUrl: null,
    },
    {
        id: 'm-charlene',
        name: 'Charlene',
        designer: 'maggie-sottero',
        designerLabel: 'Maggie Sottero',
        style: 'sheath',
        color: '#f5f5ef',
        description: 'Modern sheath with illusion long sleeves',
        imageUrl: null,
    },
    {
        id: 'm-kirstie',
        name: 'Kirstie',
        designer: 'maggie-sottero',
        designerLabel: 'Maggie Sottero',
        style: 'ballgown',
        color: '#fff0f5',
        description: 'Dreamy ballgown with layered tulle skirt',
        imageUrl: null,
    },
    {
        id: 'm-haze',
        name: 'Haze',
        designer: 'maggie-sottero',
        designerLabel: 'Maggie Sottero',
        style: 'aline',
        color: '#f8f6f0',
        description: 'Soft A-line with lace appliqué hem',
        imageUrl: null,
    },

    /* ── RICHARD DESIGNS ────────────────────────────────────────── */
    {
        id: 'r-naomi',
        name: 'Naomi',
        designer: 'richard-designs',
        designerLabel: 'Richard Designs',
        style: 'mermaid',
        color: '#f0f5f0',
        description: 'Elegant mermaid with floral organza detail',
        imageUrl: null,
    },
    {
        id: 'r-sophia',
        name: 'Sophia',
        designer: 'richard-designs',
        designerLabel: 'Richard Designs',
        style: 'aline',
        color: '#f8f5ef',
        description: 'Classic A-line with beaded bodice and chapel train',
        imageUrl: null,
    },
    {
        id: 'r-grace',
        name: 'Grace',
        designer: 'richard-designs',
        designerLabel: 'Richard Designs',
        style: 'ballgown',
        color: '#fff5fb',
        description: 'Timeless ballgown with full tulle skirt',
        imageUrl: null,
    },
    {
        id: 'r-isabella',
        name: 'Isabella',
        designer: 'richard-designs',
        designerLabel: 'Richard Designs',
        style: 'sheath',
        color: '#f0f0f5',
        description: 'Sleek sheath with lace back and sweep train',
        imageUrl: null,
    },
    {
        id: 'r-charlotte',
        name: 'Charlotte',
        designer: 'richard-designs',
        designerLabel: 'Richard Designs',
        style: 'aline',
        color: '#f5f8f0',
        description: 'Romantic A-line with soft chiffon layers',
        imageUrl: null,
    },
    {
        id: 'r-victoria',
        name: 'Victoria',
        designer: 'richard-designs',
        designerLabel: 'Richard Designs',
        style: 'ballgown',
        color: '#fdf8f5',
        description: 'Grand ballgown with embellished corset bodice',
        imageUrl: null,
    },
];
